version: '3.7'
services:
  mysql:
    # to use on Apple M1 chip, add platform
    #platform: linux/amd64
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playground
  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
    container_name: redis
  api:
    # Dockerfile for the java app "api" is in same folder, so use .
    build: .
    image: api
    container_name: api
    ports:
      - "8080:8080"
    # trick to force condition check (if mysql/redis are not ready yet, api will restart until they are ready)
    restart: on-failure