version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    privileged: true
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playground
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    container_name: redis
  api:
    # Dockerfile for app is in same folder, so use .
    build: .
    image: api
    container_name: api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    # force container startup sequence, but no guarantee on container availability (readyness to use)
    depends_on:
      - mysql
      - redis
    # trick to force condition check (e.g. if mysql is not ready to use, api will restart)
    restart: on-failure
    links:
      - redis:redis
      - mysql:redis