spring:
  datasource:
    url: jdbc:mysql://mysql:3306/playground?&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0.0
    host: redis
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379