spring:
  profiles:
    active: @activatedProperties@
  flyway:
    locations: classpath:migration
mybatis-plus:
  # xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.neo.model
  global-config:
    db-config:
      id-type: assign_id
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      # logic-delete-field: delete_status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑删除
      logic-not-delete-value: 0 # 正常
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false